### ISSUE TITLE
Failures not handled: OrderService JVM failure, network partitioning between OrderService and database

### ISSUE THREAD

**Issue by serg3k** [giova333/transactional-messaging#1]
Approach, presented in the [article](https://www.up-2date.com/post/transactional-messaging-polling-publisher) and implemented in this repo is able to handle **Kafka Cluster failure**, or **network partitioning between OrderService and Kafka Broker**.
 
What is still being neglected is **OrderService JVM failure** or **network partitioning between OrderService and database**: 
Imagine what will happen if after [OrderCreationService, Line#15](https://github.com/giova333/transactional-messaging/blob/main/polling-publisher/src/main/java/com/gladunalexander/pollingpublisher/orderservice/OrderCreationService.java#L15) has been executed one of the following happen: JVM is crashed, k8s restarts the pod or network connection between _OrderService_ and db is interrupted.
Line#16 will not be executed, and _OrderCreatedEvent_ will not be persisted in Database, hence it will not be processed by _KafkaEventPublisher_, and will not be published into Kafka, never reaching _DeliveryService_.
 
Solution to this problem, that comes to my mind is to execute these two database queries as single DB transaction:
 * Save _Order_ to `orders` table
 * Save _OrderCreatedEvent_ to `outbox` table

In this way, event and order record are guaranteed to be persisted together in the database, and event will reach _DeliveryService_.

**Comment by giova333** [comment]
Hi @sergi-ko. Thanks, it's a very good point. I was sure that `OrderCreationService.create` was executed inside a transaction but apparently, I forgot to add the `@Transactional`.

**Comment by giova333** [comment]
Fix: https://github.com/giova333/transactional-messaging/commit/c93048277f254936d35caed974ed12b736be9b6b
